services:
  pulseaudio:
    env_file: ".env"
    build: pulseaudio/.
    restart: unless-stopped
    image: ronaldvk90/pulseaudio
    volumes:
      - pulsesocket:/tmp/
      - /var/run/avahi-daemon:/var/run/avahi-daemon
      - /var/run/dbus:/var/run/dbus
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev:ro
    hostname: pulseaudio
    ports:
      - "4713:4713"
    devices:
      - /dev/snd:/dev/snd
  shairport-sync:
    env_file: .env
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    volumes:
      - pulsesocket:/tmp/
      - /etc/localtime:/etc/localtime:ro
      - ./shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file. Needed for pulse backend
    network_mode: "host"
    hostname: bakruis
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  spotify:
    image: ronaldvk90/spotify
    build: spotify/.
    volumes:
      - pulsesocket:/tmp/
      - /etc/localtime:/etc/localtime:ro
    hostname: bakruis
    env_file: ".env"
    restart: unless-stopped
    network_mode: host
volumes:
  pulsesocket:
