#!/bin/sh

DONE=""

while true; do
    SINKS=$(pactl list short sinks | awk '{print $2}')

    for SINK in $SINKS; do
        echo "$DONE" | grep -q "^$SINK$" || {
            pactl set-sink-volume "$SINK" 100%
            DONE="${DONE}
$SINK"
        }
    done

    sleep 2
done